repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.39.0
    hooks:
      - id: golangci-lint
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt