version: '3'

services:
  db:
    build:
      context: .
      dockerfile: db.dockerfile

    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: root
      POSTGRES_DB: opencollab

volumes:
  dbdata: