version: '3'

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: root
      POSTGRES_DB: opencollab

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
    - redisdata:/data

volumes:
  dbdata:
  redisdata: